version: "2"
services:
  web:
    container_name: ${CONTAINER_NAME}
    restart: always
    build: .
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - CONTAINER_NAME=${CONTAINER_NAME}
networks:
  default:
    external:
      name: service-tier